version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: erpvanbanco
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - senhas.env
    ports:
      - "5432:5432"
    restart: always